### ISSUE TITLE
Not working with Hype Gallery

### ISSUE THREAD

**Issue by merilturock** [hypeJunction/hypeLists#4]
Hypelist is not working with hype gallery as when i go to hype gallery by enabling hype list the next page button is not visible in hype gallery.

**Comment by Daltonmedia** [comment]
Noticed this as well today.
It's not hypegallery, it's just the page/components/gallery view that doesn't get initialised by the plugins js init function (it looks for the class 'elgg-list' to trigger and since gallery views in Elgg don't have that class the view uses the 'elgg-gallery' class nothing get triggered.
A quick (and dirty) fix to fix this without touching hypeLists code or hypeGallery its code is to add the class 'elgg-list' to Elgg's page/components/gallery.php view by overriding that view in a custom plugin with just that view in it.

Copy the file page/components/gallery.php to a plugin and change line 36: $list_classes = ['elgg-gallery']; to $list_classes = ['elgg-gallery elgg-list'];
and the hypegallery lists will be ajaxified.

Note that this is just a temporary solution untill there is a real fix in the hypeLists code.

**Comment by hypeJunction** [comment]
Thanks for looking into this. I will patch it up.

**Comment by hypeJunction** [comment]
should be resolved
